### ISSUE TITLE
Certain Excel files formats cause crashes. 

### ISSUE THREAD

**Issue by alwalt** [alwalt/Semantic-List-Matching-with-LLMs#1]
In line 288, using the file "sample_nbisc.xlsx" causes a crash with the uploaded test file "example_pi.xlsx". Not sure if it's because there aren't any values under the column names for "sample_nbisc.xlsx"? 

`Traceback (most recent call last):
  File "/Users/woalvara/Documents/OSDR/code/Semantic-List-Matching-with-LLMs/gui_test.py", line 50, in run
    self.process()
  File "/Users/woalvara/Documents/OSDR/code/Semantic-List-Matching-with-LLMs/gui_test.py", line 44, in process
    self.emit_data.emit((self.table1, self.table2, self.replace_text, self.match_to_color, self.dict_matches, self.is_matched, self.matches))
AttributeError: 'Worker' object has no attribute 'match_to_color'
zsh: abort      python3 gui_test.py
`

**Comment by babypastorkayvon** [comment]
Just fixed the the issue with no data/values under the column names. Thanks for the catch.
